version: '3.7'

services:
  db:
    image: postgres:12.2
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lfivxwpybbsuez
      POSTGRES_PASSWORD: 57e2446834ba4157f634019185d0d382afb539495325752fbea76150453e4e6e
      POSTGRES_DB: dcdldfsa6gr68b
volumes:
  db:
