version: '3.7'
services:
  db:
    image: postgres:12.2
    networks:
      backend:
        aliases:
          - db-testing
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Spoon
  backend:
    image: spoon-and-fork-backend
    build: .
    networks:
      - backend
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      NODE_ENV: testing
      DATABASE_HOST: ec2-46-137-177-160.eu-west-1.compute.amazonaws.com
      DATABASE_PORT: 5432
      DATABASE_USERNAME: lfivxwpybbsuez
      DATABASE_PASSWORD: 57e2446834ba4157f634019185d0d382afb539495325752fbea76150453e4e6e
      DATABASE_NAME: dcdldfsa6gr68b
      PORT: 3000
volumes:
  db:
networks:
  backend:
