version: '3.7'

services:
  db:
    image: postgres:12.2
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: exchange_backyard
      POSTGRES_PASSWORD: magicmore
      POSTGRES_DB: exchange
volumes:
  db:
